---
- name: Add Timezone Current Place
  lineinfile:
    path: /etc/opt/rh/rh-php73/php.ini
    regexp: '^date.timezone'
    line: date.timezone = Asia/Jakarta

- name: Enable Service rh-php73-php-fpm
  service:
    name: rh-php73-php-fpm
    enabled: yes

- name: Start Service Icingaweb2
  service:
    name: rh-php73-php-fpm
    state: started
