---
# - name: Disable Galera Cluster Check from Known XInetD Services
#   lineinfile:
#     path: /etc/services
#     insertafter: '^# Local services'
#     line: 'mysqlchk    9200/tcp      # MySQL Check'
#     state: absent

# - name: Uninstall Galera Cluster Check Scripts (XInetD)
#   file:
#     path: /etc/xinetd.d/mysqlchk
#     state: absent

# - name: Uninstall Galera Cluster Check Scripts (Binary)
#   file:
#     path: /usr/bin/clustercheck
#     state: absent

- name: Uninstall MariaDB Packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - mariadb-server
    - mariadb
    - MySQL-python
  # when:
  #   - galera_distribution == 'percona'

# - name: Uninstall Galera Repository
#   apt:
#     name: "{{ item }}"
#     force_apt_get: yes
#     purge: yes
#     state: absent
#   with_items:
#     - percona-release
  # when:
  #   - galera_distribution == 'percona'
