---

- name: Find Exsisting Nginx Logs
  find:
    paths: /var/log/nginx
    recurse: yes
  register: nginx_logs

- name: Display all file nginx logs
  debug:
    msg: File is {{ nginx_logs }}
  
- name: Remove Exsisting Nginx Logs
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ nginx_logs['files'] }}"

- name: Find Exsisting Nginx Configurations
  find:
    paths: /etc/nginx/conf.d
    recurse: yes
  register: nginx_configs

- name: Display all file nginx conf
  debug:
    msg: File is {{ nginx_configs }}


- name: Remove Exsisting Nginx Configurations
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items:
    - "{{ nginx_configs['files'] }}"

# - name: Remove Exsisting Nginx Configurations Directory
#   file:
#     path: /etc/nginx
#     state: absent
