---
- name: Set Host Facts
  set_fact:
    icinga_db_password: "{{ icinga_db_password | default(default_value, true) }}"
    mariadb_admin_password: "{{ mariadb_admin_password | default(default_value, true) }}"
